{{- /* gotype: github.com/entkit/entkit.Generator */ -}}

{{- define "../Dockerfile" -}}
{{- $.Extension.FileHeader | ER_replace "^" "#" }}

FROM golang:1.19-alpine

WORKDIR /app
ADD . /app

# Deps
RUN apk add --no-cache alpine-sdk
RUN apk add --no-cache nodejs npm

# Build
RUN go mod tidy
RUN go build -o /usr/local/bin/entkit ./{{$.Name}}/*.go

# Run binary
ENTRYPOINT ["/bin/sh", "-c"]

# Command
CMD ["entkit"]

{{- end -}}